export const stepsOfTheMonth = [
  {
    month: 1,
    step: 1,
    title: 'Step One',
    subtitle: 'Acceptance & Honesty',
    description: 'We admitted we were powerless over alcohol—that our lives had become unmanageable.',
    focus: 'Lean into honesty and allow trusted people to support your first steps toward change.',
    image: '/images/step1.png',
    workLink: '/steps/1',
  },
  {
    month: 2,
    step: 2,
    title: 'Step Two',
    subtitle: 'Hope & Possibility',
    description: 'Came to believe that a Power greater than ourselves could restore us to sanity.',
    focus: 'Let hope in. Explore practices that reconnect you with community and spiritual guidance.',
    image: '/images/step2.png',
    workLink: '/steps/2',
  },
  {
    month: 3,
    step: 3,
    title: 'Step Three',
    subtitle: 'Trust & Surrender',
    description: 'Made a decision to turn our will and our lives over to the care of God as we understood Him.',
    focus: 'Practice letting go through prayer, meditation, or conversations with your sponsor.',
    image: '/images/step3.png',
    workLink: '/steps/3',
  },
  {
    month: 4,
    step: 4,
    title: 'Step Four',
    subtitle: 'Courage & Inventory',
    description: 'Made a searching and fearless moral inventory of ourselves.',
    focus: 'Use structured tools to explore resentments, fears, and relationships with compassion.',
    image: '/images/step4.png',
    workLink: '/step4',
  },
  {
    month: 5,
    step: 5,
    title: 'Step Five',
    subtitle: 'Integrity & Healing',
    description: 'Admitted to God, to ourselves, and to another human being the exact nature of our wrongs.',
    focus: 'Share your inventory in a safe setting. Let vulnerability open the door to healing.',
    image: '/images/step5.png',
    workLink: '/steps/5',
  },
  {
    month: 6,
    step: 6,
    title: 'Step Six',
    subtitle: 'Readiness & Willingness',
    description: 'Were entirely ready to have God remove all these defects of character.',
    focus: 'Notice where old patterns still linger and imagine what life looks like without them.',
    image: '/images/step6.png',
    workLink: '/steps/6',
  },
  {
    month: 7,
    step: 7,
    title: 'Step Seven',
    subtitle: 'Humility & Growth',
    description: 'Humbly asked Him to remove our shortcomings.',
    focus: 'Practice humility through service, gratitude, and daily spiritual contact.',
    image: '/images/step7.png',
    workLink: '/steps/7',
  },
  {
    month: 8,
    step: 8,
    title: 'Step Eight',
    subtitle: 'Preparation & Compassion',
    description: 'Made a list of all persons we had harmed, and became willing to make amends to them all.',
    focus: 'Craft your list with care, honoring both accountability and personal safety.',
    image: '/images/step8.png',
    workLink: '/steps/8',
  },
  {
    month: 9,
    step: 9,
    title: 'Step Nine',
    subtitle: 'Amends & Repair',
    description: 'Made direct amends to such people wherever possible, except when to do so would injure them or others.',
    focus: 'Work with your sponsor to plan amends that respect boundaries and foster healing.',
    image: '/images/step9.png',
    workLink: '/steps/9',
  },
  {
    month: 10,
    step: 10,
    title: 'Step Ten',
    subtitle: 'Daily Practice',
    description: 'Continued to take personal inventory and when we were wrong promptly admitted it.',
    focus: 'Keep a short list. Use nightly inventories and journaling to stay grounded.',
    image: '/images/step10.png',
    workLink: '/steps/10',
  },
  {
    month: 11,
    step: 11,
    title: 'Step Eleven',
    subtitle: 'Prayer & Meditation',
    description: 'Sought through prayer and meditation to improve our conscious contact with God as we understood Him, praying only for knowledge of His will for us and the power to carry that out.',
    focus: 'Experiment with quiet time, guided meditations, or gratitude lists to deepen connection.',
    image: '/images/step11.png',
    workLink: '/steps/11',
  },
  {
    month: 12,
    step: 12,
    title: 'Step Twelve',
    subtitle: 'Service & Fellowship',
    description: 'Having had a spiritual awakening as the result of these Steps, we tried to carry this message to alcoholics, and to practice these principles in all our affairs.',
    focus: 'Share your experience, strength, and hope. Look for ways to serve and stay connected.',
    image: '/images/step12.png',
    workLink: '/steps/12',
  },
];

