import mongoose from 'mongoose';

/**
 * MongoDB model for Art Generation History
 *
 * Tracks all art generation requests made by the Ghibli Art Director Agent.
 * Provides audit trail and analytics for art generation activities.
 */
const ArtGenerationHistorySchema = new mongoose.Schema({
  // Request metadata
  request_id: {
    type: String,
    required: false, // Will be auto-generated by pre-save hook
    unique: true,
    index: true,
  },

  // What was requested
  request_type: {
    type: String,
    enum: ['batch_daily', 'single_daily', 'step_set', 'single_step', 'badge', 'seasonal', 'manual', 'single'],
    required: true,
    index: true,
  },

  // Trigger information
  trigger: {
    type: {
      type: String,
      enum: ['scheduled', 'manual', 'api', 'on-demand', 'backfill'],
      required: true,
    },
    initiated_by: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    initiated_at: { type: Date, default: Date.now },
  },

  // Generation scope
  scope: {
    art_type: {
      type: String,
      enum: ['daily_reflection', 'step_illustration', 'milestone_badge', 'seasonal_graphic', 'custom'],
    },
    // For batch operations
    batch_size: Number,
    items: [{
      reference_key: String,
      reference_value: String,
    }],
  },

  // Execution tracking
  execution: {
    started_at: Date,
    completed_at: Date,
    duration_ms: Number,
    agent_run_id: String, // LangGraph execution ID
  },

  // Results
  results: {
    total_requested: {
      type: Number,
      default: 0,
    },
    successful: {
      type: Number,
      default: 0,
    },
    failed: {
      type: Number,
      default: 0,
    },
    skipped: {
      type: Number,
      default: 0,
    },
    // References to generated art
    generated_art_ids: [{
      type: mongoose.Schema.Types.ObjectId,
      ref: 'GeneratedArt',
    }],
  },

  // Cost tracking
  costs: {
    total_api_calls: {
      type: Number,
      default: 0,
    },
    total_cost_usd: {
      type: Number,
      default: 0,
    },
    breakdown: [{
      model: String,
      calls: Number,
      cost_usd: Number,
    }],
  },

  // Status
  status: {
    type: String,
    enum: ['queued', 'running', 'completed', 'partial', 'failed', 'cancelled'],
    default: 'queued',
    index: true,
  },

  // Errors and warnings
  errors: [{
    timestamp: Date,
    error_type: String,
    message: String,
    item_reference: String,
  }],
  warnings: [{
    timestamp: Date,
    warning_type: String,
    message: String,
  }],

  // Configuration used
  configuration: {
    ghibli_style_level: {
      type: String,
      enum: ['subtle', 'moderate', 'strong'],
      default: 'moderate',
    },
    quality_setting: {
      type: String,
      enum: ['standard', 'hd'],
      default: 'standard',
    },
    auto_approve: Boolean,
    manual_review_required: Boolean,
  },

  // Admin notes
  notes: String,
  cancelled_reason: String,
}, {
  timestamps: true, // Adds createdAt and updatedAt
  suppressReservedKeysWarning: true, // Suppress warning for 'errors' field
});

// Indexes for efficient querying
ArtGenerationHistorySchema.index({ request_type: 1, status: 1 });
ArtGenerationHistorySchema.index({ 'trigger.type': 1, createdAt: -1 });
ArtGenerationHistorySchema.index({ 'execution.started_at': -1 });
ArtGenerationHistorySchema.index({ createdAt: -1 });

// Virtual for success rate
ArtGenerationHistorySchema.virtual('success_rate').get(function() {
  if (this.results.total_requested === 0) return 0;
  return (this.results.successful / this.results.total_requested) * 100;
});

// Method to record generation start
ArtGenerationHistorySchema.methods.markStarted = function(agentRunId) {
  this.status = 'running';
  this.execution.started_at = new Date();
  this.execution.agent_run_id = agentRunId;
  return this.save();
};

// Method to record successful generation
ArtGenerationHistorySchema.methods.recordSuccess = function(artId, costUsd) {
  this.results.successful += 1;
  this.results.generated_art_ids.push(artId);
  this.costs.total_api_calls += 1;
  this.costs.total_cost_usd += costUsd;
  return this.save();
};

// Method to record failure
ArtGenerationHistorySchema.methods.recordFailure = function(itemReference, errorType, errorMessage) {
  this.results.failed += 1;
  this.errors.push({
    timestamp: new Date(),
    error_type: errorType,
    message: errorMessage,
    item_reference: itemReference,
  });
  return this.save();
};

// Method to record skip
ArtGenerationHistorySchema.methods.recordSkip = function(reason) {
  this.results.skipped += 1;
  this.warnings.push({
    timestamp: new Date(),
    warning_type: 'skipped',
    message: reason,
  });
  return this.save();
};

// Method to complete generation
ArtGenerationHistorySchema.methods.markCompleted = function() {
  this.execution.completed_at = new Date();
  this.execution.duration_ms = this.execution.completed_at - this.execution.started_at;

  // Determine final status
  if (this.results.failed === this.results.total_requested) {
    this.status = 'failed';
  } else if (this.results.failed > 0) {
    this.status = 'partial';
  } else {
    this.status = 'completed';
  }

  return this.save();
};

// Static method to get generation stats
ArtGenerationHistorySchema.statics.getGenerationStats = async function(startDate, endDate) {
  const stats = await this.aggregate([
    {
      $match: {
        'execution.started_at': {
          $gte: startDate,
          $lte: endDate,
        },
        status: { $in: ['completed', 'partial'] },
      },
    },
    {
      $group: {
        _id: null,
        total_requests: { $sum: 1 },
        total_generated: { $sum: '$results.successful' },
        total_failed: { $sum: '$results.failed' },
        total_cost: { $sum: '$costs.total_cost_usd' },
        avg_duration_ms: { $avg: '$execution.duration_ms' },
      },
    },
  ]);

  return stats[0] || {
    total_requests: 0,
    total_generated: 0,
    total_failed: 0,
    total_cost: 0,
    avg_duration_ms: 0,
  };
};

// Static method to get recent history
ArtGenerationHistorySchema.statics.getRecentHistory = function(limit = 20) {
  return this.find()
    .sort({ createdAt: -1 })
    .limit(limit)
    .exec();
};

// Pre-save hook to set request_id
ArtGenerationHistorySchema.pre('save', function(next) {
  if (!this.request_id) {
    const timestamp = Date.now();
    const random = Math.random().toString(36).substring(2, 8);
    this.request_id = `gen_${this.request_type}_${timestamp}_${random}`;
  }
  next();
});

export default mongoose.models.ArtGenerationHistory || mongoose.model('ArtGenerationHistory', ArtGenerationHistorySchema);
